# Generated by Django 4.0.3 on 2022-04-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='user.balance'),
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='user.category'),
        ),
    ]
