# Generated by Django 4.0.3 on 2022-04-08 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_data_account_alter_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 8, 4, 16, 46, 176635)),
        ),
    ]
