# Generated by Django 4.0.3 on 2022-04-08 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 8, 7, 29, 5, 793804)),
        ),
    ]
