# Generated by Django 4.0.3 on 2022-04-08 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_balance_account_alter_balance_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 8, 7, 30, 35, 718694)),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
